/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ae4dd353-5743-4867-833a-962b4d63433c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_G9YUNqFxN",
    "aws_user_pools_web_client_id": "57i3ke67ia9nsc6cvlg238j9lg",
    "oauth": {},
    "aws_content_delivery_bucket": "batchvizapp-20210102093123-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://batchvizapp-20210102093123-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
